Mute Crowdin and failure-check for testing

diff --git a/.github/workflows/build-beta.yml b/.github/workflows/build-beta.yml
--- a/.github/workflows/build-beta.yml
+++ b/.github/workflows/build-beta.yml
@@ -350,92 +350,92 @@ jobs:
               --username "$APPLE_ID_USERNAME" --password "$APPLE_ID_PASSWORD"
 
 
-  crowdin-push:
-    name: Crowdin Push
-    if: github.ref == 'refs/heads/main'
-    needs:
-      - ios
-    runs-on: ubuntu-22.04
-    env:
-      _CROWDIN_PROJECT_ID: "269690"
-    steps:
-      - name: Checkout repo
-        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+  # crowdin-push:
+  #   name: Crowdin Push
+  #   if: github.ref == 'refs/heads/main'
+  #   needs:
+  #     - ios
+  #   runs-on: ubuntu-22.04
+  #   env:
+  #     _CROWDIN_PROJECT_ID: "269690"
+  #   steps:
+  #     - name: Checkout repo
+  #       uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
 
-      - name: Login to Azure - CI Subscription
-        uses: Azure/login@e15b166166a8746d1a47596803bd8c1b595455cf # v1.6.0
-        with:
-          creds: ${{ secrets.AZURE_KV_CI_SERVICE_PRINCIPAL }}
+  #     - name: Login to Azure - CI Subscription
+  #       uses: Azure/login@e15b166166a8746d1a47596803bd8c1b595455cf # v1.6.0
+  #       with:
+  #         creds: ${{ secrets.AZURE_KV_CI_SERVICE_PRINCIPAL }}
 
-      - name: Retrieve secrets
-        id: retrieve-secrets
-        uses: bitwarden/gh-actions/get-keyvault-secrets@main
-        with:
-          keyvault: "bitwarden-ci"
-          secrets: "crowdin-api-token"
+  #     - name: Retrieve secrets
+  #       id: retrieve-secrets
+  #       uses: bitwarden/gh-actions/get-keyvault-secrets@main
+  #       with:
+  #         keyvault: "bitwarden-ci"
+  #         secrets: "crowdin-api-token"
 
-      - name: Upload Sources
-        uses: crowdin/github-action@198daeb2d30636c4608d6a6bb96c009dbefc02a2 # v1.18.0
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          CROWDIN_API_TOKEN: ${{ steps.retrieve-secrets.outputs.crowdin-api-token }}
-        with:
-          config: crowdin.yml
-          crowdin_branch_name: main 
-          upload_sources: true
-          upload_translations: false
+  #     - name: Upload Sources
+  #       uses: crowdin/github-action@198daeb2d30636c4608d6a6bb96c009dbefc02a2 # v1.18.0
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #         CROWDIN_API_TOKEN: ${{ steps.retrieve-secrets.outputs.crowdin-api-token }}
+  #       with:
+  #         config: crowdin.yml
+  #         crowdin_branch_name: main 
+  #         upload_sources: true
+  #         upload_translations: false
 
 
-  check-failures:
-    name: Check for failures
-    if: always()
-    runs-on: ubuntu-22.04
-    needs:
-      - ios
-      - crowdin-push
-    steps:
-      - name: Check if any job failed
-        if: |
-          (github.ref == 'refs/heads/main')
-          || (github.ref == 'refs/heads/rc')
-          || (github.ref == 'refs/heads/hotfix-rc')
-        env:
-          CLOC_STATUS: ${{ needs.cloc.result }}
-          ANDROID_STATUS: ${{ needs.android.result }}
-          F_DROID_STATUS: ${{ needs.f-droid.result }}
-          IOS_STATUS: ${{ needs.ios.result }}
-          CROWDIN_PUSH_STATUS: ${{ needs.crowdin-push.result }}
-        run: |
-          if [ "$CLOC_STATUS" = "failure" ]; then
-              exit 1
-          elif [ "$ANDROID_STATUS" = "failure" ]; then
-              exit 1
-          elif [ "$F_DROID_STATUS" = "failure" ]; then
-              exit 1
-          elif [ "$IOS_STATUS" = "failure" ]; then
-              exit 1
-          elif [ "$CROWDIN_PUSH_STATUS" = "failure" ]; then
-              exit 1
-          fi
+  # check-failures:
+  #   name: Check for failures
+  #   if: always()
+  #   runs-on: ubuntu-22.04
+  #   needs:
+  #     - ios
+  #     - crowdin-push
+  #   steps:
+  #     - name: Check if any job failed
+  #       if: |
+  #         (github.ref == 'refs/heads/main')
+  #         || (github.ref == 'refs/heads/rc')
+  #         || (github.ref == 'refs/heads/hotfix-rc')
+  #       env:
+  #         CLOC_STATUS: ${{ needs.cloc.result }}
+  #         ANDROID_STATUS: ${{ needs.android.result }}
+  #         F_DROID_STATUS: ${{ needs.f-droid.result }}
+  #         IOS_STATUS: ${{ needs.ios.result }}
+  #         CROWDIN_PUSH_STATUS: ${{ needs.crowdin-push.result }}
+  #       run: |
+  #         if [ "$CLOC_STATUS" = "failure" ]; then
+  #             exit 1
+  #         elif [ "$ANDROID_STATUS" = "failure" ]; then
+  #             exit 1
+  #         elif [ "$F_DROID_STATUS" = "failure" ]; then
+  #             exit 1
+  #         elif [ "$IOS_STATUS" = "failure" ]; then
+  #             exit 1
+  #         elif [ "$CROWDIN_PUSH_STATUS" = "failure" ]; then
+  #             exit 1
+  #         fi
 
-      - name: Login to Azure - CI Subscription
-        uses: Azure/login@e15b166166a8746d1a47596803bd8c1b595455cf # v1.6.0
-        if: failure()
-        with:
-          creds: ${{ secrets.AZURE_KV_CI_SERVICE_PRINCIPAL }}
+  #     - name: Login to Azure - CI Subscription
+  #       uses: Azure/login@e15b166166a8746d1a47596803bd8c1b595455cf # v1.6.0
+  #       if: failure()
+  #       with:
+  #         creds: ${{ secrets.AZURE_KV_CI_SERVICE_PRINCIPAL }}
 
-      - name: Retrieve secrets
-        id: retrieve-secrets
-        uses: bitwarden/gh-actions/get-keyvault-secrets@main
-        if: failure()
-        with:
-          keyvault: "bitwarden-ci"
-          secrets: "devops-alerts-slack-webhook-url"
+  #     - name: Retrieve secrets
+  #       id: retrieve-secrets
+  #       uses: bitwarden/gh-actions/get-keyvault-secrets@main
+  #       if: failure()
+  #       with:
+  #         keyvault: "bitwarden-ci"
+  #         secrets: "devops-alerts-slack-webhook-url"
 
-      - name: Notify Slack on failure
-        uses: act10ns/slack@ed1309ab9862e57e9e583e51c7889486b9a00b0f # v2.0.0
-        if: failure()
-        env:
-          SLACK_WEBHOOK_URL: ${{ steps.retrieve-secrets.outputs.devops-alerts-slack-webhook-url }}
-        with:
-          status: ${{ job.status }}
+  #     - name: Notify Slack on failure
+  #       uses: act10ns/slack@ed1309ab9862e57e9e583e51c7889486b9a00b0f # v2.0.0
+  #       if: failure()
+  #       env:
+  #         SLACK_WEBHOOK_URL: ${{ steps.retrieve-secrets.outputs.devops-alerts-slack-webhook-url }}
+  #       with:
+  #         status: ${{ job.status }}
